### PR TITLE
Fixing/improving `workdaysFromDate`, add `isHoliday`, `isSpecialDay`

### PR DESCRIPTION
**Pull request by maranomynet**
Includes:
- `workdaysFromDate` improvements:
  - Fix: Always return new `Date` object
  - fix: Correctly cross year boundries
  - Handle negative day offsets, for "n-th workday _before_ {Date}"
  - Add third `includeHalfDays` boolean parameter
- Fix: Set summer and winter solstice date timestamp to 00:00
- Add convenience methods `isHoliday` and `isSpecialDay`
- Better support for named `import`s from esm projects (`pkg.type === 'module'`)

### CODE REVIEW

**Comment by maranomynet** [comment]
@gaui have you had time to look at this?

**Review by bjarkig82 — APPROVED** [review]

**Comment by maranomynet** [comment]
Bored ☕️ on a Saturday morning, and since this has not been reviewed and merged yet, I might as well add `isHoliday` and `isSpecialDay` for convenience/giggles.

**Comment by maranomynet** [comment]
@gaui ping

**Comment by maranomynet** [comment]
@gaui if you need a co-maintainer/co-owner for this package, I'm willing to help out.

**Comment by gaui** [comment]
> @gaui if you need a co-maintainer/co-owner for this package, I'm willing to help out.

@maranomynet Sorry for the late reply. I haven't been maintaining this package for a long time, just fell through the gaps. But there's a lot that can be refactored and modernized (e.g. TypeScript/ESM). Honestly I haven't had time to do it and don't see any free time in the near future, so co-ownership of the package would be appreciated. Let me know and I'll hand over the keys.

**Comment by maranomynet** [comment]
I'm game.

**Comment by maranomynet** [comment]
@gaui how should we do this? let me know what info you need from me.
BTW, this is me on npmjs.com: https://www.npmjs.com/~maranomynet

**Comment by maranomynet** [comment]
I'm personally familiar with how stress and mental-load works, so I understand…

As it's now been four months with no communication (and 8 months since this PR was opened) I've decided to, respectfully, fork this repo and (re)publish the package under a new npm package name, `holidays-is`. (Full credit given, of course!)

I plan to spend some time between jóladagur and gamlársdagur geeking around. I sincerely hope I hear from you before then.

Best wishes, take care, and happy winter solstice!

[**UPDATE:** [Here is a todo list](https://github.com/maranomynet/fridagar-node/issues/1) tracking my progress]

**Comment by maranomynet** [comment]
BTW, googling reveals this:

It seems that if you log into npmjs.com and go to a package's "Settings" panel ([example](https://www.npmjs.com/package/fridagar/access)) you can add a maintainer by typing in their npm username and clicking "Invite".

_(Source: https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account)_

Adding a collaborator to a public git repo is a similar process: Go to a repo's Settings ⟶ Collaborators ([example](https://github.com/gaui/fridagar-node/settings/access)) and click the "Add people" button.

**Comment by gaui** [comment]
@maranomynet I have added you to the npm org `gaui` (pending invite) and as a contributor on this repository (pending invite). I think a better approach would be to create a new org for the npm package. Until we find a new home for it, you should be able to publish to it there. Btw I didn't find any package named `holidays-is`.

**Comment by maranomynet** [comment]
I don't think I need to be part of your org on npmjs.com
You should be able to simply add me as a maintainer of the package.

```
npm owner add maranomynet fridagar
```

I think that way we're both maintainers and can both publish new versions.

Let me know if you still want me to accept this org invitation.

**Comment by maranomynet** [comment]
…on second thought, I'm accepting the org invite.
This automatically makes me a collaborator on all of your packages, which is not exactly ideal.

But as you say, there's plenty of time to change this later.

**Comment by maranomynet** [comment]
> Btw I didn't find any package named `holidays-is`.

That's because I decided to not publish it yet.

**Pull request merged**
